jobs:
- job: powershell_win2022
    pool:
      vmImage: windows-2022
    steps:
    - powershell: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/output/testResults.xml'
        testRunTitle: 'PS_Win2022'
      displayName: 'Publish Test Results'

  - job: pwsh_win2022
    pool:
      vmImage: windows-2022
    steps:
    - pwsh: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/output/testResults.xml'
        testRunTitle: 'PS_Win2022'
      displayName: 'Publish Test Results'

  - job: powershell_win2019
    pool:
      vmImage: windows-2019
    steps:
    - powershell: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/output/testResults.xml'
        testRunTitle: 'PS_Win2019'
      displayName: 'Publish Test Results'

  - job: pwsh_win2019
    pool:
      vmImage: windows-2019
    steps:
    - pwsh: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/output/testResults.xml'
        testRunTitle: 'PS_Win2019'
      displayName: 'Publish Test Results'

  - job: pwsh_ubuntu1604
    pool:
      vmImage: ubuntu-16.04
    steps:
    - pwsh: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/output/testResults.xml'
        testRunTitle: 'PSCore_Ubuntu1604'
      displayName: 'Publish Test Results'

  - job: pwsh_ubuntu
    pool:
      vmImage: ubuntu-latest
    steps:
    - pwsh: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/output/testResults.xml'
        testRunTitle: 'PSCore_Ubuntu'
      displayName: 'Publish Test Results'

  - job: pwsh_macos
    pool:
      vmImage: macOS-latest
    steps:
    - pwsh: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/output/testResults.xml'
        testRunTitle: 'PSCore_MacOS'
      displayName: 'Publish Test Results'
