project_id: '810132'
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /l10n/en-US.yml
    translation: /l10n/%locale%.yml
  - source: /l10n/en-US.yml
    translation: /l10n/%two_letters_code%.yml
