"project_id": "810132"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files": [
  {
    "source": "/src/en-US/",
    "translation": "/src/%locale%/%original_file_name%"
  },
]
